const CONFIG = {
  empresa: "Milhas Plus",
  titulo: "Cadastre suas",
  tituloDestaque: "contas",
  subtitulo: "Preencha os dados das contas Smiles e Livelo.",
  rodape: "Milhas Plus © 2026",
  mensagemSucesso: "Contas registradas com sucesso!",
  appsScriptUrl: "COLE_A_URL_DO_SCRIPT_AQUI",
  permitirImportacao: true,
  permitirConsulta: true,
  camposResponsavel: [
    { id: "parceiroResp", coluna: "B", label: "Parceiro responsável",      placeholder: "Seu nome completo",      tipo: "text" },
    { id: "telResp",      coluna: "C", label: "Telefone (parceiro resp.)", placeholder: "(21) 99999-9999",        tipo: "tel" },
    { id: "pixResp",      coluna: "Q", label: "Pix parceiro responsável",  placeholder: "CPF, email ou telefone", tipo: "text" },
  ],
  camposConta: [
    { id: "nomeTitular",   coluna: "D", label: "Nome titular da conta",                   placeholder: "Nome completo",     tipo: "text" },
    { id: "dataNasc",      coluna: "E", label: "Data de nascimento (titular)",             placeholder: "DD/MM/AAAA",        tipo: "data" },
    { id: "telTitular",    coluna: "F", label: "Telefone (titular da conta)",              placeholder: "(21) 99999-9999",   tipo: "tel" },
    { id: "emailConta",    coluna: "G", label: "E-mail (registrado na conta)",             placeholder: "email@exemplo.com", tipo: "email" },
    { id: "loginSmiles",   coluna: "H", label: "Login Smiles",                             placeholder: "email ou CPF",      tipo: "text" },
    { id: "senhaSmiles",   coluna: "I", label: "Senha Smiles",                             placeholder: "••••••••",          tipo: "senha" },
    { id: "loginLivelo",   coluna: "J", label: "Login Livelo",                             placeholder: "email ou CPF",      tipo: "text" },
    { id: "senhaLivelo",   coluna: "K", label: "Senha Livelo",                             placeholder: "••••••••",          tipo: "senha" },
    { id: "prazo",         coluna: "L", label: "Prazo de pagamento (conta cheia)",         placeholder: "Ex: 30 dias",       tipo: "text" },
    { id: "contaCheia",    coluna: "M", label: "Conta cheia?",                             placeholder: "",                  tipo: "select", opcoes: ["Sim", "Não"] },
    { id: "cartaoProprio", coluna: "N", label: "Cartão próprio usado no clube?",           placeholder: "",                  tipo: "select", opcoes: ["Sim", "Não"] },
    { id: "cartaoMP",      coluna: "O", label: "Cartão MP utilizado (últimos dígitos)",    placeholder: "Ex: 1234",          tipo: "text", condicional: { campo: "cartaoProprio", valor: "Não" } },
    { id: "dataClube",     coluna: "P", label: "Data da assinatura do clube",              placeholder: "DD/MM/AAAA",        tipo: "data" },
  ],
  exemploImport: [
    "Leo Silva", "(21) 98765-4321", "Maria Santos", "15/06/1990",
    "(21) 91234-5678", "maria@gmail.com", "maria@gmail.com", "Senha123!",
    "maria@gmail.com", "Livelo456@", "30 dias", "Sim", "Não", "5678",
    "01/01/2025", "(21) 98765-4321"
  ],
  cores: {
    primaria:   "#1A3C34",
    destaque:   "#F2D645",
    fundo:      "#FAFAF6",
    cardFundo:  "#ffffff",
    texto:      "#1A3C34",
    textoSuave: "#6a8a80",
    inputFundo: "#FAFAF6",
    inputBorda: "#e0ddd5",
    erroCor:    "#dc2626",
  },
};
export default CONFIG;
